# Generated by Django 5.2.11 on 2026-03-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("model",)},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("first_name", "last_name")},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",)},
        ),
    ]
